print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
//print("hello world")//
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
function main{}{
  return null;
}
